// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm } from "emdash";

export interface PageContentMarketingHeroV1Block {
  _type: "marketing_hero";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "eyebrow"?: string | null;
  "headline": string;
  "subheadline"?: string | null;
  "primary_cta_label"?: string | null;
  "primary_cta_url"?: string | null;
  "secondary_cta_label"?: string | null;
  "secondary_cta_url"?: string | null;
}

export type PageContentMarketingHeroBlock = PageContentMarketingHeroV1Block;

export interface PageContentMarketingFeaturesV1Block {
  _type: "marketing_features";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "eyebrow"?: string | null;
  "headline": string;
  "subheadline"?: string | null;
  "features": { "number": string; "label": string; "title": string; "description": string }[];
}

export type PageContentMarketingFeaturesBlock = PageContentMarketingFeaturesV1Block;

export interface PageContentMarketingCtaV1Block {
  _type: "marketing_cta";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "eyebrow"?: string | null;
  "headline": string;
  "subheadline"?: string | null;
  "button_label": string;
  "button_url"?: string | null;
}

export type PageContentMarketingCtaBlock = PageContentMarketingCtaV1Block;

export type PageContentBlock = PageContentMarketingHeroBlock | PageContentMarketingFeaturesBlock | PageContentMarketingCtaBlock;

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PageContentBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
  }
}